logging:
  file: logs/mod-camunda.log
  level:
    org:
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO
  path:

server:
  port: 9000

spring:
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true
  datasource:
    platform: h2
    url: jdbc:h2:./target/mod-camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    # platform: postgres
    # driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/mod-camunda
    
    username: folio
    password: folio
  h2:
    console: 
      enabled: true
      path: /h2console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    open-in-view: true
    show-sql: false
  profiles:
    active: default
  thymeleaf:
    mode: TEXT
    suffix: .sql

camunda:
  bpm:
    admin-user:
      id: bboring
      password: password
      first-name: Bob
      last-name: Boring
      email: bboring@mailinator.com
      # authorization.enabled: true

additional:
  domain-packages:
  # https://github.com/camunda/camunda-bpm-platform/tree/master/engine/src/main/resources/org/camunda/bpm/engine/db/create
  # be sure to match datasource platform
  schema-scripts:
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.identity.sql
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.case.engine.sql
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.case.history.sql
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.decision.engine.sql
    - classpath:/org/camunda/bpm/engine/db/create/activiti.h2.create.decision.history.sql
